# Record name
name: Category

# Model Form Field configuration
form: $/octoshop/categories/models/category/fields.yaml

# Model Class name
modelClass: Octoshop\Categories\Models\Category

# Default redirect location
defaultRedirect: octoshop/categories/categories

# Create page
create:
    title: octoshop.categories::lang.categories.title_create
    redirect: octoshop/categories/categories/update/:id
    redirectClose: octoshop/categories/categories

# Update page
update:
    title: octoshop.categories::lang.categories.title_update
    redirect: octoshop/categories/categories
    redirectClose: octoshop/categories/categories
