categories:
    label: Category
    view:
        list: $/octoshop/categories/models/category/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        showSearch: true
        recordsPerPage: 10
        list: $/octoshop/categories/models/category/columns.yaml
        form: $/octoshop/categories/models/category/fields.yaml
